use_frameworks!

platform :ios, '8.0'

target 'LYHEntertainingDiversions-OC_Example' do
  pod 'LYHEntertainingDiversions-OC', :path => '../'

  target 'LYHEntertainingDiversions-OC_Tests' do
    inherit! :search_paths

    
  end
end
